apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: staging
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/mateo-burillo-ns/promcat-frontend:staging
        ports:
        - containerPort: 3000
        env:
          - name: BASE_URL
            value: http://frontend:3000
          - name: API_URL
            value: http://backend:8080
